version: '3'

services:
  scrolls:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/static

