# Generated by Django 4.1.7 on 2023-03-16 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email address",
                    ),
                ),
                ("otp", models.PositiveIntegerField(default=123456)),
                ("is_team", models.BooleanField(default=False)),
                ("is_member", models.BooleanField(default=False)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email address",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("college", models.CharField(max_length=350, null=True)),
                ("course", models.CharField(max_length=150, null=True)),
                ("branch", models.CharField(blank=True, max_length=150)),
                ("year_of_study", models.PositiveIntegerField(null=True)),
                ("member_id", models.CharField(blank=True, max_length=250)),
                ("referral_code", models.CharField(blank=True, max_length=250)),
                ("is_ambassador", models.BooleanField(default=False)),
                ("referral_count", models.PositiveIntegerField(default=0)),
                ("password", models.CharField(max_length=10000000000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True, unique=True)),
                (
                    "size",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(3),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("team_id", models.CharField(blank=True, max_length=250)),
                ("topic", models.CharField(blank=True, max_length=1500)),
                ("domain", models.CharField(blank=True, max_length=150)),
                ("referral_used", models.CharField(blank=True, max_length=15)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "leader_id",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="leader",
                        to="participants.participant",
                    ),
                ),
                (
                    "member_2",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="member_2",
                        to="participants.participant",
                    ),
                ),
                (
                    "member_3",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="member_3",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
