# Generated by Django 4.1.7 on 2023-03-05 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email address",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=150)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("college", models.CharField(default=None, max_length=350)),
                ("course", models.CharField(max_length=150)),
                ("branch", models.CharField(blank=True, max_length=150)),
                ("member_id", models.CharField(default=None, max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
