# Generated by Django 4.1.7 on 2023-03-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="mobile",
            field=models.IntegerField(null=True),
        ),
    ]
