# Generated by Django 4.1.7 on 2023-03-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="member_id",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
