# Generated by Django 4.1.7 on 2023-03-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_alter_participant_member_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="year_of_study",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
