# Generated by Django 4.1.7 on 2023-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_participant_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="paper",
            field=models.FileField(default="", upload_to="static/media"),
        ),
        migrations.AddField(
            model_name="team",
            name="synopsis",
            field=models.FileField(default="", upload_to="static/media"),
        ),
    ]
