# Generated by Django 4.1.7 on 2023-03-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_participant_year_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="college",
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name="participant",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
