# Generated by Django 4.1.7 on 2023-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0004_alter_team_paper_alter_team_synopsis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
