# Generated by Django 4.1.7 on 2023-03-22 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0005_alter_participant_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="year_of_study",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(4),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
