# Generated by Django 4.1.7 on 2023-03-20 07:22

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0005_alter_participant_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="paper",
            field=models.FileField(
                default="",
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="media",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="synopsis",
            field=models.FileField(
                default="",
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="media",
            ),
        ),
    ]
