# Generated by Django 4.1.7 on 2023-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0006_alter_participant_year_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="paper",
            field=models.FileField(default="", upload_to=""),
        ),
        migrations.AlterField(
            model_name="team",
            name="synopsis",
            field=models.FileField(default="", upload_to=""),
        ),
    ]
