# Generated by Django 4.1.7 on 2023-03-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0006_alter_participant_year_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Management Science", "Management Science"),
                    (
                        "Electrical and Electronics Engineering",
                        "Electrical and Electronics Engineering",
                    ),
                    ("Civil Engineering", "Civil Engineering"),
                    (
                        "Electronics and Communication Engineering",
                        "Electronics and Communication Engineering",
                    ),
                    ("Mechanical Engineering", "Mechanical Engineering"),
                    (
                        "Computer Science and Information Technology",
                        "Computer Science and Information Technology",
                    ),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="paper",
            field=models.FileField(default="", upload_to="hide/paper"),
        ),
        migrations.AlterField(
            model_name="team",
            name="synopsis",
            field=models.FileField(default="", upload_to=""),
        ),
    ]
