# Generated by Django 4.1.7 on 2023-03-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0006_participant_mobile_alter_participant_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="mobile",
            field=models.PositiveIntegerField(),
        ),
    ]
