# Generated by Django 4.1.7 on 2023-03-31 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0007_alter_team_domain_alter_team_paper_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration_Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="path",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="team",
            name="member_3",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="member_3",
                to="participants.participant",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="paper",
            field=models.FileField(blank=True, default="", upload_to=""),
        ),
        migrations.AlterField(
            model_name="team",
            name="synopsis",
            field=models.FileField(blank=True, default="", upload_to=""),
        ),
    ]
