# Generated by Django 4.1.7 on 2023-04-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0008_registration_check_team_is_selected_team_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="path",
        ),
    ]
