# Generated by Django 4.1.7 on 2023-03-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0008_participant_is_ambassador_participant_referral_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
