# Generated by Django 4.1.7 on 2023-03-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0010_participant_is_registered"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="referral_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
