# Generated by Django 4.1.7 on 2024-03-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0010_alter_team_paper_alter_team_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='domain',
            field=models.CharField(blank=True, choices=[('Management Science', 'Management_Science'), ('Electrical and Electronics Engineering', 'Electrical_and_Electronics_Engineering'), ('Civil Engineering', 'Civil_Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Science and Information Technology', 'Computer Science and Information Technology')], max_length=150),
        ),
    ]
