# Generated by Django 4.1.7 on 2023-03-09 03:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0011_participant_referral_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="domain",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="team",
            name="leader_id",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="leader",
                to="participants.participant",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="member_2",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="member_2",
                to="participants.participant",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="member_3",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="member_3",
                to="participants.participant",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="team",
            name="password",
            field=models.CharField(max_length=10000000000, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="referral_used",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="team",
            name="size",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(3),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="team_id",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="team",
            name="topic",
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
