# Generated by Django 4.1.7 on 2023-03-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0014_alter_participant_year_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="college",
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="course",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Others")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="mobile",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="participant",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
