# Generated by Django 4.1.7 on 2023-03-13 10:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0016_participant_is_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, null=True, unique=True)),
                (
                    "size",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(3),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("team_id", models.CharField(blank=True, max_length=250)),
                ("topic", models.CharField(blank=True, max_length=1500)),
                ("domain", models.CharField(blank=True, max_length=150)),
                ("referral_used", models.CharField(blank=True, max_length=15)),
                ("password", models.CharField(max_length=10000000000, null=True)),
                (
                    "leader_id",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="lead",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_2",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="member2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member_3",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="member3",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
