# Generated by Django 4.1.7 on 2023-03-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0018_teams_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
