# Generated by Django 4.1.7 on 2023-03-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0019_team_last_login"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teams",
        ),
    ]
