# Generated by Django 4.1.7 on 2023-03-14 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0020_delete_teams"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="email address",
                    ),
                ),
                ("otp", models.PositiveIntegerField(default=123456)),
                ("is_team", models.BooleanField(default=False)),
                ("is_member", models.BooleanField(default=False)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
