# Generated by Django 4.1.7 on 2023-03-14 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0021_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="email",
            field=models.EmailField(
                max_length=255,
                validators=[django.core.validators.EmailValidator()],
                verbose_name="email address",
            ),
        ),
    ]
